In [ ]:
import pandas as pd

from configs import (
    FREQDICT_FILE, ANKIFREQ_FILE,
    RANK_COL, LEMMA_COL, FREQUENCY_COL, POS_COL, WORD_COL,
    MAX_RANK_TO_ADD, MIN_RANK_TO_REMOVE,
    ANKI_WORD_FIELD, ANKI_NOTETYPE_COL,
    ANKI_TO_KEEP_FILE, ANKI_TO_ADD_FILE, ANKI_TO_REMOVE_FILE,
)

In [2]:
df = pd.read_csv(FREQDICT_FILE)

df

,word,frequency,lemma,morph,pos,rank
0,das,5502675,der,Case=Nom|Definite=Def|Gender=Neut|Number=Sing|...,DET,1
1,dem,5502675,der,Case=Dat|Definite=Def|Gender=Masc|Number=Sing|...,DET,1
2,dessen,5502675,der,Case=Gen|Number=Sing|PronType=Dem,PRON,1
3,der,5502675,der,Case=Nom|Definite=Def|Gender=Masc|Number=Sing|...,DET,1
4,ders,5502675,der,Case=Gen|Number=Sing,PROPN,1
...,...,...,...,...,...,...
1152561,lamik,1,lamik,Case=Nom|Gender=Fem|Number=Sing,NOUN,565801
1152562,lamich,1,lamich,Case=Nom|Gender=Masc|Number=Sing,NOUN,565801
1152563,aaaa,1,aaaa,Case=Nom|Gender=Masc|Number=Sing,NOUN,565801
1152564,ﬂiegenden,1,ﬂiegend,VerbForm=Inf,VERB,565801
1152565,ﬂiege,1,ﬂiege,Case=Nom|Gender=Fem|Number=Sing,PROPN,565801

In [3]:
df_anki = pd.read_csv(ANKIFREQ_FILE)

df_anki

,notetype,Deutsch,word,lemma,frequency,rank
0,My-German-Preposition,ab,ab,ab,52266,378
1,My-German-Verb,abbiegen,abbiegen,abbiegen,432,23089
2,My-German-PragmaticExpression,Guten Abend,abend,abend,6236,3379
3,My-German-Noun,das Abendessen,abendessen,abendessen,586,19078
4,My-German-Noun,das Abenteuer,abenteuer,abenteuer,1326,11369
...,...,...,...,...,...,...
2626,My-German-Noun,die Übersetzung,übersetzung,übersetzung,704,17107
2627,My-German-Verb,überweisen,überweisen,überweisen,779,16019
2628,My-German-Adverb,üblich,üblich,üblich,2694,6925
2629,My-German-Adverb,übrigens,übrigens,übrigens,3447,5688
2630,My-German-Noun,die Übung,übung,übung,892,14750

# Filtering the top ranking lemmas

In [4]:
top_lemmas = df[(df[RANK_COL] <= MAX_RANK_TO_ADD) & (df[FREQUENCY_COL] > 0)][LEMMA_COL].unique()
anki_lemmas = df_anki[LEMMA_COL].unique()
anki_lemmas_in_top = df_anki[(df_anki[RANK_COL] < MAX_RANK_TO_ADD) & (df_anki[FREQUENCY_COL] > 0)][LEMMA_COL].unique()
anki_lemmas_in_acceptable = df_anki[(df_anki[RANK_COL] <= MIN_RANK_TO_REMOVE) & (df_anki[RANK_COL] > MAX_RANK_TO_ADD)][LEMMA_COL].unique()
anki_lemmas_to_keep = df_anki[(df_anki[RANK_COL] <= MIN_RANK_TO_REMOVE) & (df_anki[FREQUENCY_COL] > 0)][LEMMA_COL].unique()
anki_lemmas_to_remove = df_anki[(df_anki[RANK_COL] > MIN_RANK_TO_REMOVE) | (df_anki[FREQUENCY_COL] == 0)][LEMMA_COL].unique()
top_lemmas_missing_in_anki = set(top_lemmas) - set(anki_lemmas_to_keep)

In [5]:
print("Summary of lemma comparison between Anki and top frequency list:")
print(f"Optiomal rank: {MAX_RANK_TO_ADD}")
print(f"Acceptable rank: {MIN_RANK_TO_REMOVE}")
print(f"Total top lemmas: {len(top_lemmas)}")
print(f"Total Anki lemmas: {len(anki_lemmas)}")
print(f"Total Anki lemmas of optimal rank: {len(anki_lemmas_in_top)}")
print(f"Total Anki lemmas of acceptable rank: {len(anki_lemmas_in_acceptable)}")

Summary of lemma comparison between Anki and top frequency list:
Optiomal rank: 5000
Acceptable rank: 10000
Total top lemmas: 1201
Total Anki lemmas: 2555
Total Anki lemmas of optimal rank: 749
Total Anki lemmas of acceptable rank: 434

In [6]:
anki_keep = df_anki[df_anki[LEMMA_COL].isin(anki_lemmas_to_keep)]
anki_remove = df_anki[df_anki[LEMMA_COL].isin(anki_lemmas_to_remove)]
anki_add = df[df[LEMMA_COL].isin(top_lemmas_missing_in_anki)]

# Lemmas to keep

In [7]:
anki_keep = anki_keep[[ANKI_NOTETYPE_COL, ANKI_WORD_FIELD, LEMMA_COL, RANK_COL]].sort_values(by=[ANKI_NOTETYPE_COL, ANKI_WORD_FIELD])

print(f"Total Anki lemmas to keep: {len(anki_lemmas_to_keep)}")
anki_keep

Total Anki lemmas to keep: 1183

                 notetype       Deutsch         lemma  rank
47    My-German-Adjective     allgemein     allgemein  2376
51    My-German-Adjective           alt           alt   525
54    My-German-Adjective     am besten            an    65
290   My-German-Adjective     am besten           gut   178
58    My-German-Adjective  amerikanisch  amerikanisch  5746
...                   ...           ...           ...   ...
2599       My-German-Verb        zählen        zählen  2053
2602       My-German-Verb        ändern        ändern  2391
2609       My-German-Verb        öffnen        öffnen  2369
2613       My-German-Verb          üben          üben  7414
2618       My-German-Verb     überlegen     überlegen  7704

[1254 rows x 4 columns]

# Lemmas to add

In [8]:
anki_add.groupby(POS_COL)[LEMMA_COL].nunique()

pos
ADJ      128
ADP        5
ADV      132
AUX        6
CCONJ      2
DET        8
NOUN     164
NUM        8
PRON      26
PROPN     85
SCONJ      2
VERB     118
X         10
Name: lemma, dtype: int64

In [9]:
def filter_by_pos(df, pos):
    return df[df[POS_COL] == pos].sort_values(by=WORD_COL)

def filter_by_single_pos(df, pos):
    df_local = df.copy()
    df_local['POS_count'] = df_local.groupby(LEMMA_COL)[POS_COL].transform('nunique')
    return df_local[(df_local[POS_COL] == pos) & (df_local['POS_count'] == 1)].sort_values(by=WORD_COL)

### Pos: X

In [10]:
filter_by_single_pos(anki_add, 'X')

         word  frequency    lemma        morph pos  rank  POS_count
4018  cookies       5127  cookies  Foreign=Yes   X  4019          1
3833       fc       5363       fc          NaN   X  3834          1
4661      nrw       4389      nrw          NaN   X  4662          1

In [11]:
# Remove all the instances with pos 'X' from anki_add
anki_add = anki_add[anki_add[POS_COL] != 'X']

## Pos: SCONJ

In [12]:
filter_by_single_pos(anki_add, 'SCONJ')

       word  frequency  lemma         morph    pos  rank  POS_count
1740  warum      11973  warum  PronType=Int  SCONJ  1741          1
984      wo      20666     wo  PronType=Int  SCONJ   985          1

## Pos: AUX

In [13]:
filter_by_single_pos(anki_add, 'AUX')

,word,frequency,lemma,morph,pos,rank,POS_count
2837,kannst,7289,könnsten,Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbF...,AUX,2838,1
404,muss,45435,mussen,Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbF...,AUX,404,1
403,mussen,45435,mussen,Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbF...,AUX,404,1
2323,musste,8908,musste,Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbF...,AUX,2324,1

In [14]:
# Remove all the instances with pos 'AUX' from anki_add
anki_add = anki_add[anki_add[POS_COL] != 'AUX']

## Pos: DET

In [15]:
filter_by_single_pos(anki_add, 'DET')

,word,frequency,lemma,morph,pos,rank,POS_count
3924,all,5231,all,PronType=Ind,DET,3925,1
639,mein,31983,mein,Case=Nom|Gender=Neut|Number=Sing|Poss=Yes|Pron...,DET,639,1
638,meine,31983,mein,Case=Nom|Gender=Fem|Number=Sing|Poss=Yes|PronT...,DET,639,1
640,meinem,31983,mein,Case=Dat|Gender=Masc|Number=Sing|Poss=Yes|Pron...,DET,639,1
641,meiner,31983,mein,Case=Dat|Gender=Fem|Number=Sing|Poss=Yes|PronT...,DET,639,1
198,unser,98462,unser,Case=Nom|Gender=Neut|Number=Sing|Poss=Yes|Pron...,DET,197,1
202,unsere,98462,unser,Case=Nom|Gender=Fem|Number=Sing|Poss=Yes|PronT...,DET,197,1
201,unserem,98462,unser,Case=Dat|Gender=Neut|Number=Sing|Poss=Yes|Pron...,DET,197,1
199,unseren,98462,unser,Case=Acc|Gender=Masc|Number=Sing|Poss=Yes|Pron...,DET,197,1
203,unserer,98462,unser,Case=Dat|Gender=Fem|Number=Sing|Poss=Yes|PronT...,DET,197,1
200,unseres,98462,unser,Case=Gen|Gender=Masc|Number=Sing|Poss=Yes|Pron...,DET,197,1
197,unserm,98462,unser,Case=Dat|Gender=Masc|Number=Sing|Poss=Yes|Pron...,DET,197,1
196,unsers,98462,unser,Case=Nom|Gender=Neut|Number=Sing|Poss=Yes|Pron...,DET,197,1

In [16]:
filter_by_pos(anki_add, 'DET')[WORD_COL].unique()

<StringArray>
[    'all',   'allen',   'aller',    'dein',   'deine',  'deinem',  'deinen',
  'deiner',  'deines',   'diese',  'diesem',  'diesen',  'dieses',    'ihre',
   'ihrem',   'ihren',   'ihrer',   'ihres',    'mein',   'meine',  'meinem',
  'meiner',   'unser',  'unsere', 'unserem', 'unseren', 'unserer', 'unseres',
  'unserm',  'unsers',  'welche', 'welchem', 'welchen', 'welches']
Length: 34, dtype: str

In [17]:
# Remove all the instances with pos 'DET' from anki_add
anki_add = anki_add[anki_add[POS_COL] != 'DET']

## Pos: ADP

In [18]:
filter_by_single_pos(anki_add, 'ADP')

,word,frequency,lemma,morph,pos,rank,POS_count
1727,aufgrund,12206,aufgrund,NaN,ADP,1728,1
2165,hinter,9444,hinter,NaN,ADP,2165,1
2164,hinterm,9444,hinter,Case=Dat|Gender=Masc|Number=Sing,ADP,2165,1
2166,hinters,9444,hinter,Case=Acc|Gender=Neut|Number=Sing,ADP,2165,1
1731,innerhalb,12100,innerhalb,NaN,ADP,1732,1
1640,per,12784,per,NaN,ADP,1641,1
4610,zufolge,4468,zufolge,NaN,ADP,4611,1

## Pos: NUM

In [19]:
filter_by_single_pos(anki_add, 'NUM')

      word  frequency lemma morph  pos  rank  POS_count
1129  vier      18639  vier   NaN  NUM  1130          1
1907  zehn      10895  zehn   NaN  NUM  1908          1

In [20]:
filter_by_pos(anki_add, 'NUM')

        word  frequency   lemma morph  pos  rank
3161    acht       6672    acht   NaN  NUM  3160
593     drei      34135    drei   NaN  NUM   592
1437    fünf      14767    fünf   NaN  NUM  1438
2019   sechs      10374   sechs   NaN  NUM  2019
3196  sieben       6614  sieben   NaN  NUM  3197
1129    vier      18639    vier   NaN  NUM  1130
1907    zehn      10895    zehn   NaN  NUM  1908
379     zwei      49440    zwei   NaN  NUM   379

In [21]:
# Remove all the lemmas of instances with pos 'NUM' from anki_add, regardless of their pos
anki_add = anki_add[~anki_add[LEMMA_COL].isin(filter_by_pos(anki_add, 'NUM')[LEMMA_COL].unique())]

## Pos: PRON

In [22]:
filter_by_single_pos(anki_add, 'PRON').sort_values(by=LEMMA_COL)

,word,frequency,lemma,morph,pos,rank,POS_count
2048,dich,10177,dich,Case=Acc|Number=Sing|Person=2|PronType=Prs|Ref...,PRON,2049,1
103,dies,290732,dieser,Case=Nom|Gender=Neut|Number=Sing|PronType=Dem,PRON,100,1
101,dieser,290732,dieser,Case=Nom|Gender=Masc|Number=Sing|PronType=Dem,PRON,100,1
127,er,157523,er,Case=Nom|Gender=Masc|Number=Sing|Person=3|Pron...,PRON,128,1
2188,euch,9335,euch,Case=Dat|Number=Plur|Person=2|PronType=Prs,PRON,2189,1
1226,ihm,17166,ihm,Case=Dat|Gender=Masc|Number=Sing|Person=3|Pron...,PRON,1227,1
1063,ihn,19477,ihn,Case=Acc|Gender=Masc|Number=Sing|Person=3|Pron...,PRON,1064,1
491,ihnen,39439,ihnen,Case=Dat|Number=Plur|Person=3|PronType=Prs,PRON,492,1
986,mehrere,20522,mehrere,Case=Nom|Number=Plur|PronType=Ind,PRON,986,1
987,mehreren,20522,mehrere,Case=Dat|Gender=Neut|Number=Plur|PronType=Ind,PRON,986,1
985,mehrerer,20522,mehrere,Case=Nom|Gender=Masc|Number=Sing|PronType=Ind,PRON,986,1
888,wenige,23075,weniger,Case=Nom|Number=Plur|PronType=Ind,PRON,886,1
887,wenigen,23075,weniger,Case=Nom|Number=Plur|PronType=Ind,PRON,886,1
886,weniger,23075,weniger,PronType=Ind,PRON,886,1
885,weniges,23075,weniger,Case=Nom|Gender=Neut|Number=Sing|PronType=Ind,PRON,886,1
709,wer,29117,wer,Case=Nom|Gender=Masc|Number=Sing|PronType=Int,PRON,710,1

In [23]:
lemmas_to_keep = ["mehrere", "weniger", "wer"]

# Remove all the lemmas of instances with pos 'PRON' from anki_add, if lemma is not in lemmas_to_keep
anki_add = anki_add[
    (~anki_add[LEMMA_COL].isin(filter_by_pos(anki_add, 'PRON')[LEMMA_COL].unique())) | (anki_add[LEMMA_COL].isin(lemmas_to_keep))]

## Filtering by unique limmas and word types

In [24]:
anki_add = anki_add.drop_duplicates(subset=[LEMMA_COL, POS_COL], keep="first")

## List of lemmas to add

In [25]:
anki_add = anki_add[[WORD_COL, LEMMA_COL, POS_COL, RANK_COL]].sort_values(by=[LEMMA_COL, POS_COL])

print(f"Total top lemmas missing from Anki: {len(top_lemmas_missing_in_anki)}")
anki_add

Total top lemmas missing from Anki: 452

             word       lemma   pos  rank
3428    abschluss   abschluss  NOUN  3429
1885      aktivem       aktiv   ADJ  1886
1889        aktiv       aktiv   ADV  1886
4570  aktivitäten   aktivität  NOUN  4571
626    aktuellere     aktuell   ADJ   627
...           ...         ...   ...   ...
1534   übernehmen  übernehmen  VERB  1535
4769  überprüften  überprüfen  VERB  4770
4758  übertragene  übertragen   ADJ  4757
4756   übertragen  übertragen  VERB  4757
3341  überzeugten  überzeugen  VERB  3342

[609 rows x 4 columns]

# Lemmas to remove

In [26]:
anki_remove = anki_remove[[ANKI_NOTETYPE_COL, ANKI_WORD_FIELD, LEMMA_COL, RANK_COL]].sort_values(by=[ANKI_NOTETYPE_COL, ANKI_WORD_FIELD])

print(f"Total Anki lemmas to remove: {len(anki_lemmas_to_remove)}")
anki_remove

Total Anki lemmas to remove: 1372

                 notetype      Deutsch        lemma    rank
12    My-German-Adjective   abgesperrt    absperren   33015
33    My-German-Adjective   agnostisch   agnostisch  565801
64    My-German-Adjective        ander        ander  134193
72    My-German-Adjective   angewidert     anwidern  161333
100   My-German-Adjective  anstrengend  anstrengend   15779
...                   ...          ...          ...     ...
2605       My-German-Verb       ärgern       ärgern   17375
2620       My-German-Verb  übernachten  übernachten   22857
2621       My-German-Verb   überqueren   überqueren   20591
2625       My-German-Verb   übersetzen   übersetzen   12343
2627       My-German-Verb   überweisen   überweisen   16019

[1377 rows x 4 columns]

# Exporting the output

In [ ]:
anki_add.to_csv()